# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e3d3b9f163ffb6f38428f6252d63933a3ff0103cdfcdbaacfa2006f4e701c15d74cf24c64bed484eba1c009b3d610857962a17c620aa4c7a0a6bbca5fc0ddc

test:
  secret_key_base: a3ef431d78510c19ab0c5e4c6b509639ee3262e1fbcf3930d38eeec46ac0fccade3088f57e0c5161f510e370275eb5cd429214923f9dc10d0f5440de8bc967b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
